### ISSUE TITLE
Authentication UI

### ISSUE THREAD

**Issue by caffeine-addictt** [caffeine-addictt/greenbitessg#204]
# TODO

## Misc

- [x] #205

## Login

- [x] Errors and logs are toasted
- [x] `/login` is a generalized page showing the auth options
- Legacy `email+password`
  - [x] At route `/auth/login`
- Passkey
  - [x] At route `/auth0/login`

## Register

- [x] Errors and logs are toasted
- [x] `/register` is a generalized page showing the auth options
- Legacy
  - [x] At route `/auth/register`
  - [x] Can support DB user schema

## Activation

- [x] Errors and logs are toasted
- [x] `/activate` and `/activate/:uuid` use `authLayout`

# Acceptance criteria

- [x] Legacy register functions
- [x] Legacy login functions
- [x] Passkey login functions
